### ISSUE TITLE
react-loadable is not work

### ISSUE THREAD

**Issue by kg-dogg** [FallOutChonny/react-starter-boilerplate#1]
```javascript
import React from 'react';
import Loadable from 'react-loadable';

import App from './containers/App';
import About from './containers/About';
import NotFound from './containers/NotFound';

const Loading = (props) => {
  console.log(props);
  return <div>Loading...</div>;
};

const LoadableHome = Loadable({
  loader: () => System.import(/* webpackChunkName: 'Home' */'./containers/Home'),
  loading: Loading,
});

export default function createRoutes(/* store */) {
  return [
    {
      component: App,
      routes: [
        {
          path: '/',
          exact: true,
          component: LoadableHome,
        },
        {
          path: '/about',
          component: About,
        },
        {
          path: '*',
          component: NotFound,
        },
      ],
    },
  ];
}
```

the code splitting is not worked, why?

**Comment by FallOutChonny** [comment]
Hello,
what error message does your developer tool or terminal display?

**Comment by kg-dogg** [comment]
no errors, just only build vendor.js & main.js, should have Home.bundle.js,but there was not

**Comment by kg-dogg** [comment]
```
File sizes after gzip:

  110.34 KB  build/static/js/vendor.0a55a11c.js
  25.95 KB   build/static/css/vendor.47412f9f.css
  9.16 KB    build/static/js/main.cd1e28b2.js
```

It's my build report

**Comment by kg-dogg** [comment]
The home.js should built independence, but it's still in my main.js. I don't know why, plz help, thx

![Image of Yaktocat](https://pbs.twimg.com/media/DTtSPFRUMAAfQoX.jpg:large)

**Comment by kg-dogg** [comment]
Anyway, I just wanna make code-splitting worked. Could I have some example, like how to create a route with async load component?

**Comment by FallOutChonny** [comment]
After my test, your code splitting code is correct.
but currently react-loadable looks like not working, it's a bug, i will fix it as soon as I can, sorry.

If you want to create a route with async load, you can take a look NotFound in containers folder, and I know this module is too simple, this project is still WIP, I'll add some examples as soon as possible, such as redux, redux-saga with async load.

Very thanks for your using and feedback.

**Comment by kg-dogg** [comment]
And thank you for your help, your project is most awesome starter that I've ever seen!

**Comment by FallOutChonny** [comment]
I have resolved this issue, react-loadable should work now, sorry take a very long time.
If you still watching and have free time, can you pull the latest code and test it fixed?
I'm grateful.

**Comment by FallOutChonny** [comment]
Closing because is resolved
