### ISSUE TITLE
can you tell me how use less or sass ?

### ISSUE THREAD

**Issue by wjun52** [FallOutChonny/react-starter-boilerplate#7]

**Comment by FallOutChonny** [comment]
Good morning, you can use it with the `CSS Modules`, for example:

`App.scss`

```
.wrapper {
  background: #f2f2f2;
}
```

`App.js`

```
import s from './App.scss';

...

render() {
  return (
    <div className={s.wrapper}>
      Hello world
    </div>
  );
}
```

`LESS` and `CSS` is the same as well

**Comment by wjun52** [comment]
npm run build

./src/containers/Home/test.scss
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

npm run dev

(node:86957) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: window is not defined
(node:86957) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wjun52** [comment]
do you speak chinese ?

**Comment by FallOutChonny** [comment]
I'm sorry for late response, a little busy currently.
this issue is resolved with PR #8, can you pull the latest code and give it a try?
if problem still exist, please report to me, thanks

**Comment by FallOutChonny** [comment]
啊，我會說中文
可以用中文討論沒問題

**Comment by FallOutChonny** [comment]
Closing this because it's fixed.
