### ISSUE TITLE
SSR Issue 

### ISSUE THREAD

**Issue by lineldcosta** [FallOutChonny/react-starter-boilerplate#9]
`Warning: Did not expect server HTML to contain a <div> in <div>.`

getting this error when i run dev server

**Comment by FallOutChonny** [comment]
Hello, this issue was resolved by #10,
please pull code and give it a try, thanks.

**Comment by lineldcosta** [comment]
Yep working fine.. what was the issue, even i am getting similar issue in my boilerplate

**Comment by lineldcosta** [comment]
Hey i removed code splitting from route level, after that issue resolved.
